## 1. Create Arrays
<br>Create a NumPy array from this list: [1, 2, 3, 4, 5]
<br>Create a 3×3 matrix of zeros
<br>Create a 3×3 matrix of ones

In [2]:
import  numpy as np

In [3]:
llist = [1,2,3,4,5]
array = np.array([1,2,3,4,5])
print("converted list to np array : ",array)

converted list to np array :  [1 2 3 4 5]


In [4]:
null_matrix= np.zeros((3,3))
print("null matrix : \n",null_matrix)


null matrix : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
identity_matix = np.ones((3,3))
print("identity matrix : \n",identity_matix)

identity matrix : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Find:

Shape<br>
<br>Number of dimensions
<br>Data type

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shpae of the array : ",arr.shape)
print("number of the dimension of the array : ",arr.ndim)
print("data type of the array : ",arr.dtype)

shpae of the array :  (2, 3)
number of the dimension of the array :  2
data type of the array :  int64


<br> Get the 3rd element
<br>Get last two elements
<br>Reverse the array

In [7]:
arr = np.array([10, 20, 30, 40, 50])
print("third element of the array : ",arr[2])
print("last two element of the arra",arr[3:5])
reversed = arr[::-1]
print("array are reversed : ",reversed)

third element of the array :  30
last two element of the arra [40 50]
array are reversed :  [50 40 30 20 10]


<br>Add both arrays
<br>Multiply element-wise
<br>Find dot product

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("adding two array : ", a+b)
print("multiply both array",a * b)
print("dot product of the both array : ",np.dot(a,b))

adding two array :  [5 7 9]
multiply both array [ 4 10 18]
dot product of the both array :  32


### Multiply all elements by 2
Find the sum and mean

In [9]:

a = np.array([1, 2, 3, 4, 5])
mul = a * 2
print("all elements multiplied by two : ",mul)

all elements multiplied by two :  [ 2  4  6  8 10]


### Extract the second row
Extract the last column
Extract a submatrix [[5,6],[8,9]]

In [12]:
mat = np.array([[1,2,3],
 [4,5,6],
 [7,8,9]])
print("extracting last column : ",mat[:,2])
print("sub matrix : ",mat[1:,1:])

extracting last column :  [3 6 9]
sub matrix :  [[5 6]
 [8 9]]


### 4. Reshaping

Create an array from 1 to 12 and reshape it into:

A 3×4 matrix
A 4×3 matrix

In [15]:
arra = np.arange(1,13)
print("original array  : ",arra)
reshaped_array = np.reshape(arra,(3,4))
print(reshaped_array)

original array  :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Extract elements greater than 20
Replace all values less than 20 with 0
Find indices of elements divisible by 5

In [21]:
arr = np.array([10, 15, 20, 25, 30, 35])
extracting = arr[arr > 20]
print("extracting all elements that are greater than 20 : ",extracting)
replaced =np.where(arr < 20 ,0,arr)
print("replacing all values with zero which are less than 20 : ",replaced)
indices = np.where(arr % 5 == 0)

print("indices of all values which are divisiable by five : ",indices)

extracting all elements that are greater than 20 :  [25 30 35]
replacing all values with zero which are less than 20 :  [ 0  0 20 25 30 35]
indices of all values which are divisiable by five :  (array([0, 1, 2, 3, 4, 5]),)
