### numpy with chai aur code
<p> numpy mean numerical python
<p> written in cpp
<p> numpy as base for more laibraries like pandas,pytorch
<p> numpy added some extra power to python language
<p> import numpy as np so np is a standard alias for refrencing to numpy

In [19]:
import numpy as np
import time

### creating array from list
<p> list and array are two diffrent concept in python 
<P> list are slower and np array are faster than list


In [20]:
one_d=np.array([1,2,3,4,5])
print("one dimensional array : ",one_d)
two_d=np.array([[1,2,3],[3,4,5]])
print("two dimensional array : ",two_d)

one dimensional array :  [1 2 3 4 5]
two dimensional array :  [[1 2 3]
 [3 4 5]]


### list vs np array

In [21]:
list=[1,2,3]
print("list multiplication : ",list * 2)
# in numpy array element wise multiplication occured
np_array=np.array([1,2,3])
print("numpy array multiplictaion : ",np_array * 2)



start=time.time()
list=[i*3 for i in range (9000000)]
print("list operation time : ",time.time()-start)

startt=time.time()
np_arrayy=np.arange(9000000) * 3
print("numpy array operation time : ",time.time()-startt)


list multiplication :  [1, 2, 3, 1, 2, 3]
numpy array multiplictaion :  [2 4 6]
list operation time :  0.4154353141784668
numpy array operation time :  0.014919281005859375


### creating array from scratch

In [22]:
ones_array=np.ones((3,3))
print("array of ones : \n",ones_array)
print("\n")

zeros_array=np.zeros((3,3))
print("array of zeros : \n",zeros_array)

print("\n")
full_array=np.full((3,3),5)
print("full array  : \n",full_array)


random=np.random.random((3,3))
print("\nrandom array :  \n",random) 

sequance_array=np.arange(0,11,2)
print("\nsequance array : ",sequance_array)

array of ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


array of zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


full array  : 
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

random array :  
 [[0.58410121 0.25875432 0.84020097]
 [0.26038008 0.26543824 0.43132955]
 [0.54233584 0.98373559 0.98764403]]

sequance array :  [ 0  2  4  6  8 10]


### vector ,matrix  ,tensors
<p> tensors mean n dimensional array

In [23]:
vector=np.array([1,2,3,4])
print("vector :",vector)

matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,4,2]])
print("\nmatrix : \n",matrix)

tensor=np.array([
    [[1,2],[3,4]],
    [[3,2],[6,2]],
    [[1,4],[9,0]]
])
print("tensors : \n",tensor)

vector : [1 2 3 4]

matrix : 
 [[1 2 3]
 [4 5 6]
 [7 4 2]]
tensors : 
 [[[1 2]
  [3 4]]

 [[3 2]
  [6 2]]

 [[1 4]
  [9 0]]]


### properties of array

In [24]:
array=np.array([[1,2,3],
                [4,3,2],
                [3,2,1]])
print("shape : ",array.shape)
print("dimension : ",array.ndim)
print("size : ",array.size) # TOTAL NUMBER OF ELEMENT IN THE ARRAY 
print("data type : ",array.dtype)

shape :  (3, 3)
dimension :  2
size :  9
data type :  int64


### array reshaping

In [25]:
array=np.arange(15)
print("orignal array  ",array)

reshaped_array=array.reshape(3,5)
print("\nreshaped array \n",reshaped_array)

flat=reshaped_array.flatten()
print("\nflatten the reshaped array : ",flat)


# raveled return vies instead of copy of the orignal array
raveled=reshaped_array.ravel()
print("\nraveled array : \n",raveled)


transpose = reshaped_array.T
print("\n transpose \n",transpose)








orignal array   [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

reshaped array 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]

flatten the reshaped array :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

raveled array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 transpose 
 [[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


### summary of the phase one 
<p> one dimensional array
<p> two dimensional array
<p> three dimensional array
<p> what is the diffrence b/w list and numpy array
<p> creating array from the scratch
<p> zeros array
<p> ones array
<p> full array
<p> random array
<p> sequance array
<p> vectors , matrices, tensors
<p> properties of array 
<p> shape
<p> size
<p> data type
<p> ndimension
<p> array reshping
<p> reshaped array
<p> flatten array
<p> revaled array which change the orignal array in created a flatten form
<p> transpose of the array mean change rows into columns and columns into rows