# phase four 

In [4]:
import numpy as np
import matplotlib.pyplot as plt

In [5]:
array1=np.array([[1,2,3],[4,5,6]])
array2=np.random.rand(3,3)
array3=np.zeros((4,4))

### save data into file 

In [6]:
np.save('array1.npy',array1)
np.save('array2.npy',array2)
np.save('array3.npy',array3)

### load data from the file

In [9]:
print(np.load('array1.npy'))
print("\n")
print(np.load("array2.npy"))

[[1 2 3]
 [4 5 6]]


[[0.69301187 0.11233059 0.8948518 ]
 [0.50681762 0.33069119 0.11273143]
 [0.09079584 0.80502801 0.02920955]]
