# numpy array operations

#### basics slicing of array

In [2]:
import numpy as np

In [3]:
arrayy=np.arange(11)
print("array ",arrayy)

print("basic slicing : ",arrayy[0:8])
print("slicing with step : ",arrayy[3:9:3])
print("negative slicing : ",arrayy[-6])

array  [ 0  1  2  3  4  5  6  7  8  9 10]
basic slicing :  [0 1 2 3 4 5 6 7]
slicing with step :  [3 6]
negative slicing :  5


### two dimensional array slicing 

In [4]:
two_d=np.array([[2,3,4,5,6],
                [6,4,3,2,2],
                [6,5,4,3,9],
                [5,6,7,8,5]])
print("matrix :\n",two_d)
print("specfic  element slicing : ",two_d[2,2])
print("entire row slicing : ",two_d[3])
print("entire column : ",two_d[:,4])

print("\n\n\n")

two_d_array=np.array([[1,2,3],
                      [4,3,2],
                      [6,4,3],
                      [6,5,2]])
print("specfic element : ",two_d_array[2,0])
print("entire row : ",two_d_array[3])
print("entire column : ",two_d_array[:,2])
print("specfic element in column : ",two_d_array[3:,0])


matrix :
 [[2 3 4 5 6]
 [6 4 3 2 2]
 [6 5 4 3 9]
 [5 6 7 8 5]]
specfic  element slicing :  4
entire row slicing :  [5 6 7 8 5]
entire column :  [6 2 9 5]




specfic element :  6
entire row :  [6 5 2]
entire column :  [3 2 3 2]
specfic element in column :  [6]


### sorting array and two dimensional array 

In [5]:
unsorted_2d=np.array([[4,5],
                      [3,5],
                      [8,2]])
# when axis = 0 the array will be sorted columns wise
print("sorted array : \n",np.sort(unsorted_2d,axis=0))
# when axis = 1 the array will be sorted  row wise
print("sorted the 2d array by row wise : \n",np.sort(unsorted_2d,axis=1))

sorted array : 
 [[3 2]
 [4 5]
 [8 5]]
sorted the 2d array by row wise : 
 [[4 5]
 [3 5]
 [2 8]]


### filetering

In [6]:
array=np.array([1,2,3,4,5,6,7,8,9,10])
even_array=array[array % 2 == 0]
print("even array : ",even_array)

even array :  [ 2  4  6  8 10]


### filtering with mask

In [7]:

mask = array > 5 
print("elements greater than five : ", array[mask])

elements greater than five :  [ 6  7  8  9 10]


### fancy indexing vs where clause ()


In [8]:
indices = [0,5,2]
print("fancy indexing : ",array[indices])

# where clasue
where_result = np.where(array > 6)
print("where result : ",array[where_result])



fancy indexing :  [1 6 3]
where result :  [ 7  8  9 10]


In [9]:
conditional_array = np.where(array > 5 , 0 ,array)
print(conditional_array)

[1 2 3 4 5 0 0 0 0 0]


### adding and removing data

In [ ]:
array_one=np.array([1,2,3,4])
array_two=np.array([4,3,2,2])
adding=array_one + array_two
print("adding two array : ",adding)

combined = np.concatenate((array_one ,array_two))
print("combinig  two array : ",combined)
# deleted the element it index 2
deleted = np.delete(array_one,[2])
print("array after deltetion  : \n",deleted)


adding two array :  [5 5 5 6]
combinig  two array :  [1 2 3 4 4 3 2 2]
array after deltetion  : 
 [1 2 4]


### array compataibality

In [12]:
# cheacking array order to perform array operation like addition ,subtraction 
a = np.array([1,2,3])
b = np.array([3,2,1])
c = np.array([9,87,4,3])
print("cheacking compaitaibility : ",a.shape == b.shape)
print("cheacking compaitaibility : ",a.shape == c.shape)


cheacking compaitaibility :  True
cheacking compaitaibility :  False


### adding new row and new columns

In [ ]:
orignal = np.array([[1,2],[3,4]])
print("orignal array : \n",orignal)
# adding new row with orignal 
# vstack added new row

new_row=np.array([[5,6]])
with_new_row = np.vstack((orignal,new_row))
print("\n with new row  : \n",with_new_row)

# hstack added new column
new_column=np.array([[7],[8]])
with_new_column=np.hstack((orignal,new_column))
print("\nadded new columns : \n",with_new_column)


orignal array : 
 [[1 2]
 [3 4]]

 with new row  : 
 [[1 2]
 [3 4]
 [5 6]]

added new columns : 
 [[1 2 7]
 [3 4 8]]


## summary
basic slicing 
two dimensional array slicing <br>
one dimensional array slicing<br>
two dimesional arraya slicing<br>
in 2d array slcing occured into two types row wise and column wise<br>
filtering and filtering with mask<br>
fancy indexing  vs where clause<br>
adding and removing data <br>
array compaitaibility<br>
adding new row and new columns<br>