### problem part three

In [1]:
import numpy as np

In [4]:
array = np.arange(1,13)
print("orignal array : ",array)
reshaped = array.reshape(3,4)
print("reshaped array : \n",reshaped)

orignal array :  [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### find even number

### 

In [5]:
arr = np.array([10, 15, 20, 25, 30, 35])
even_number = arr [ arr % 2 == 0]
print("even number : ",even_number)

even number :  [10 20 30]


### row and column sum

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
row_sum=np.sum(arr,axis=1)
print("row sum : ",row_sum)
column_sum=np.sum(arr,axis=0)
print("column sum : ",column_sum)

row sum :  [ 6 15]
column sum :  [5 7 9]


### matrix multiplication 

In [11]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print("compaitability : ",A.shape == B.shape)
print("multiplication of matrix : ",np.dot(A,B))

compaitability :  True
multiplication of matrix :  [[19 22]
 [43 50]]


Create a 5×5 array of ones, then add a border of zeros around it.

In [22]:
matrix = np.ones((5,5))
matrix[0,:] = 0
matrix[4]=0
matrix[:,0]=0
matrix[:,4]=0
print(matrix)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
