### The Problem: Filtering and Normalizing a Matrix
Objective: Given a 2D NumPy array, filter out rows that contain any negative numbers, and then normalize the remaining rows so that their elements sum to 1. 
Requirements
Create a NumPy array of shape (4, 4) with random integers between -5 and 10 (inclusive).
Filter: Remove any entire row that contains at least one negative number.
Normalize: For the remaining rows, modify them in-place such that the sum of elements in each row is 1.0. 

In [2]:
import numpy as np



In [3]:
array =np.random.randint(-5,11,(4,4))
print("original array " ,array)


original array  [[-4  9 10  4]
 [ 3 -3 -2  0]
 [-1 -5  1 -5]
 [-2  9 -4  3]]


In [4]:
condition = (array >= 0).all(axis=1)
# filter
non_negative= array[condition]
print("negative array remove from the matrix : \n",non_negative)
row_sum = np.sum(non_negative,axis=1,keepdims=True)
print("\nadding row wise ",row_sum)
normalized = non_negative / row_sum
print("\nnormalize matrix " ,normalized)

negative array remove from the matrix : 
 []

adding row wise  []

normalize matrix  []


### 🔹 Problem 1: Row-wise Normalization

Create a 2D NumPy array of random integers (shape 5×4).
Normalize each row so that the sum of each row becomes 1.

👉 Hint: Use sum(axis=1, keepdims=True)

In [5]:
array = np.random.randint(0,15,(5,4))
print("original array : \n",array)
row_sum = np.sum(array,axis=1,keepdims=True)
print("\nrow_sum",row_sum)
normalized=array / row_sum
round = np.round(normalized,1)
print("\nnormalized each rows : ",round)

original array : 
 [[ 3  0  2  2]
 [ 0  5  1 11]
 [12 14  5 12]
 [ 1 13  1  9]
 [ 5 12  5  0]]

row_sum [[ 7]
 [17]
 [43]
 [24]
 [22]]

normalized each rows :  [[0.4 0.  0.3 0.3]
 [0.  0.3 0.1 0.6]
 [0.3 0.3 0.1 0.3]
 [0.  0.5 0.  0.4]
 [0.2 0.5 0.2 0. ]]


### Problem 2: Find Duplicate Rows

Given a 2D NumPy array, find all duplicate rows.

In [6]:
matrix = np.array([[1,2],
                    [3,4],
                    [1,2],
                    [5,6]])
unique_rows,count = np.unique(matrix,axis=0,return_counts=True)
duplicate_rows = unique_rows[count > 1]
print("duplicate rows  : ",duplicate_rows)



duplicate rows  :  [[1 2]]


### 🔹 Problem 3: Replace Values Based on Condition

Create an array of size (6×6) with random values from 1 to 20.
Replace:

All values divisible by 3 → -1
All values divisible by 5 → -2

In [47]:
matrix = np.random.randint(1,21,(6,6))
print("matrix : \n",matrix)

#value which are divisable by three are replaced with -1
divby3 = np.where((matrix % 3 == 0), -1,matrix)
print("\nvalue divisable by three  are replaced with -1 : \n",divby3)
#value which are divisable by five are replaced with -2
divby5 = np.where((matrix % 5 == 0),-2,matrix)
print("\nvalues are divisble by five are replaced with -2 : ",divby5)



matrix : 
 [[ 7  7 10 19 16  9]
 [ 3 15 14 18  9 14]
 [12  7  8 17 13 20]
 [17  3 12  4  4 14]
 [20  6 18 17 19 15]
 [10  4 18 18 15 11]]

value divisable by three  are replaced with -1 : 
 [[ 7  7 10 19 16 -1]
 [-1 -1 14 -1 -1 14]
 [-1  7  8 17 13 20]
 [17 -1 -1  4  4 14]
 [20 -1 -1 17 19 -1]
 [10  4 -1 -1 -1 11]]

values are divisble by five are replaced with -2 :  [[ 7  7 -2 19 16  9]
 [ 3 -2 14 18  9 14]
 [12  7  8 17 13 -2]
 [17  3 12  4  4 14]
 [-2  6 18 17 19 -2]
 [-2  4 18 18 -2 11]]


### Problem 4: Matrix Row Swap

Given a matrix:
Swap the first and last rows.

[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [69]:
matrix = np.array([[1,2,3],
                   [4,3,2],
                   [5,6,7],
                   [8,7,6],
                   [5,2,1]])
matrix [[0,4]] = matrix[[4,0]]
print("swaping ist and last rows : \n ",matrix)
# swaping row two and 0 ,row 4 and 3
matrix[[2,0,4,3]] = matrix [[0,2,3,4]]
print("swaping row two and 0 ,row 4 and 3 : \n ",matrix)

swaping ist and last rows : 
  [[5 2 1]
 [4 3 2]
 [5 6 7]
 [8 7 6]
 [1 2 3]]
swaping row two and 0 ,row 4 and 3 : 
  [[5 6 7]
 [4 3 2]
 [5 2 1]
 [1 2 3]
 [8 7 6]]
