## You are given exam scores of 5 students across 3 subjects (Math, Science, English).
Your task is to perform a series of analyses using NumPy.

In [1]:
import numpy as np

In [2]:
grades = np.array([
    [85, 90, 78],
    [92, 88, 84],
    [75, 70, 80],
    [88, 85, 89],
    [95, 93, 91]
])
# find mean of the score
mean_score_sub = np.mean(grades,axis=0)
print("mean score of the subject wise : ",mean_score_sub)
# maximum score in the subjects wise
max_score=np.max(grades,axis=0)
print("maximum score in the subject wise : ",max_score)
# minimum score in the subjects
min_score  = np.min(grades,axis=0)
print("minimum score subject wise: ",min_score)


mean score of the subject wise :  [87.  85.2 84.4]
maximum score in the subject wise :  [95 93 91]
minimum score subject wise:  [75 70 78]


## Compute for each student:

Total score (sum of all subjects)

Average score

In [3]:
total_score = np.sum(grades,axis=1)
print("total score per student : ",total_score)
average_score = np.mean(grades,axis=1)
print(average_score)

total score per student :  [253 264 225 262 279]
[84.33333333 88.         75.         87.33333333 93.        ]


## Find the student with the highest total score and their total.

In [4]:
top_student_index = np.argmax(total_score)
top_student_score = np.max(total_score)
print(f"the index of the student is {top_student_index} and the scores equall to : {top_student_score}")

the index of the student is 4 and the scores equall to : 279


## The teacher decides to add 5 bonus points to all Math scores.

In [5]:
grades[:,0] = grades[:,0] + 5
print(grades)

[[ 90  90  78]
 [ 97  88  84]
 [ 80  70  80]
 [ 93  85  89]
 [100  93  91]]


## Normalize scores (min-max scaling)



In [6]:
min_values = np.min(grades,axis=0)
max_values =np.max(grades,axis=0)
normalized = (grades - min_values)/ ( max_values - min_values)
print("grades are normalixed : ",normalized.round(3))

grades are normalixed :  [[0.5   0.87  0.   ]
 [0.85  0.783 0.462]
 [0.    0.    0.154]
 [0.65  0.652 0.846]
 [1.    1.    1.   ]]


Given an array, replace all values:

< 0 → 0
> 100 → 100
Do it without loops.

In [7]:


arr1 = np.array([-10, 5, 120, 45, -3, 200, 67])
relplaced_with_zero = np.where(arr1 < 0 ,0,arr1)
print("elements are replaced which are less than zero : ",relplaced_with_zero)
relplaced_with_hundred = np.where(arr1 > 100 ,100,arr1)
print("relplaced_with_hundred : ",relplaced_with_hundred)

elements are replaced which are less than zero :  [  0   5 120  45   0 200  67]
relplaced_with_hundred :  [-10   5 100  45  -3 100  67]


#### row wise normalization

In [8]:
arr2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
total_sum = np.sum(arr2,axis=1,keepdims=True,)
normalized = arr2/total_sum
print("noramlized : ",normalized.round(2))

noramlized :  [[0.17 0.33 0.5 ]
 [0.27 0.33 0.4 ]
 [0.29 0.33 0.38]]


### 3. Find Duplicate Rows