In [2]:
import numpy as np

### checking shape datatype and size of the array very basic problem

In [3]:
array_one =np.array([1, 2, 3, 4, 5])
print("array shape : ",array_one.shape)
print("array_one",array_one.size)
print("array_one",array_one.dtype)

array shape :  (5,)
array_one 5
array_one int64


### creating matrix of zeros and ones

In [4]:
matrix_one = np.zeros((3,4))
print("null matrix : \n",matrix_one)
matrix_two = np. ones((3,4))
print("identity matrix :\n ",matrix_two)

null matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
identity matrix :
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### creating matrix of random number between one and hundred of 4 X 4 and finding min,max,mean,sum

In [5]:
matrix_three = np.random.randint(1,100,(4,4))
print("matrix : \n",matrix_three)
print("min of the matrix : ",np.min(matrix_three))
print("max of the matrix : ",np.max(matrix_three))
print("mean of the matrix : ",np.mean(matrix_three))
print("sum of the matrix : ",np.sum(matrix_three))




matrix : 
 [[77 10  7 51]
 [48 79 10 32]
 [45 57 41 70]
 [66 59 49 17]]
min of the matrix :  7
max of the matrix :  79
mean of the matrix :  44.875
sum of the matrix :  718


## slicing

In [6]:
array_two = np.arange(10)
extract = array_two[2:7]
print("extract element from index 2 to 7 : ",extract)


extract element from index 2 to 7 :  [2 3 4 5 6]


### Create a 5x5 array with numbers 0 to 24. Extract the middle 3x3 subarray.

In [7]:
matrix_four=np.random.randint(0,24,(5,5))
print("orignal matrix :\n ",matrix_four)
extract = matrix_four[1:4,1:4]
print("\nmiddle of the matrix\n ",extract)

orignal matrix :
  [[ 4  9  9  7 15]
 [13  4  7 22  1]
 [ 9 20 13  8  0]
 [ 9 17 11 18  3]
 [ 5 23  5 10 23]]

middle of the matrix
  [[ 4  7 22]
 [20 13  8]
 [17 11 18]]


### Generate an array of 10 evenly spaced numbers between 0 and 1 (inclusive).

In [8]:
array_three = np.linspace(0,1,10)
print(array_three)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### From a 4x4 array, extract all even rows and odd columns.

In [9]:
matrix_five =np.random.randint(0,10,(4,4))
print("matrix : \n",matrix_five)
extraxt_even_rows = matrix_five[0:4:2]
print("extracting all even rows from the matrix : \n",extraxt_even_rows)
extract_odd_col=matrix_five[:,1:4:2]
print("extracting all odd columns : \n ",extract_odd_col)

result = matrix_five[0:4:2, 1:4:2]  # Rows 0,2 and Columns 1,3
print("Elements in even rows AND odd columns:")
print(result)


matrix : 
 [[2 2 9 4]
 [8 4 1 6]
 [7 3 4 8]
 [1 7 4 2]]
extracting all even rows from the matrix : 
 [[2 2 9 4]
 [7 3 4 8]]
extracting all odd columns : 
  [[2 4]
 [4 6]
 [3 8]
 [7 2]]
Elements in even rows AND odd columns:
[[2 4]
 [3 8]]


### Reshape a 1D array of 12 elements into a 3x4 matrix. Then flatten it back.

In [10]:
arr = np.arange(0,12)
print("original array :  ",arr)
print("\nreshape it to 3 X 4 : \n",arr.reshape(3,4))
print("\nflatten it back :",arr.flatten())

original array :   [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape it to 3 X 4 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flatten it back : [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stack two 2x2 arrays vertically (row-wise) and horizontally (column-wise

In [11]:
arr = np .array([[1,2],
                 [3,4]])


arrr = np.array([[3,4],
                 [5,6]])
print("array one : \n",arr)
print("\narray two : \n",arrr)
vstack =np.vstack((arr,arrr))
print("row wise  : \n",vstack)
hstack = np.hstack((arr,arrr))
print("column wise : \n",hstack)

array one : 
 [[1 2]
 [3 4]]

array two : 
 [[3 4]
 [5 6]]
row wise  : 
 [[1 2]
 [3 4]
 [3 4]
 [5 6]]
column wise : 
 [[1 2 3 4]
 [3 4 5 6]]


### 1. Normalize a 5x5 random matrix 

In [ ]:
matrix =np.random.randint(8,34,(6,6))
print("original matrix : \n",matrix)
mean_matrix = np.mean(matrix)
print("mean of the matrix : ",mean_matrix)
stddevi = np.std(matrix)
print("standard deviation of the matrix : ",stddevi)
normalized = (matrix - mean_matrix) / stddevi
print("normalized matrix : ",normalized.round(2))



original matrix : 
 [[20 25 31 30 14  8]
 [32 25 11  9 26 26]
 [33 22  9 21 20 16]
 [13 19 22 26 14 12]
 [14 33 11  9 31  8]
 [18 28 17 24 21 22]]
mean of the matrix :  20.0
standard deviation of the matrix :  7.710022337480251
normalized matrix :  [[ 0.    0.65  1.43  1.3  -0.78 -1.56]
 [ 1.56  0.65 -1.17 -1.43  0.78  0.78]
 [ 1.69  0.26 -1.43  0.13  0.   -0.52]
 [-0.91 -0.13  0.26  0.78 -0.78 -1.04]
 [-0.78  1.69 -1.17 -1.43  1.43 -1.56]
 [-0.26  1.04 -0.39  0.52  0.13  0.26]]


TypeError: 'numpy.ndarray' object is not callable