### 👉 Extract:

elements from index 1 to 4
last 3 elements
every second element

In [2]:
import numpy as np

In [3]:
arr = np.array([10, 20, 30, 40, 50, 60])
slicing = arr[1:4]
print("slicing from one to four : ",slicing)
slicing2 = arr[3:]
print("slicing last three elements : ",slicing2)
every_second_element = arr[0:5:2]
print(every_second_element)

slicing from one to four :  [20 30 40]
slicing last three elements :  [40 50 60]
[10 30 50]


👉 Extract:

first two rows
last two columns
center element

In [4]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
first_two_rows= arr[0:2]
print("first two rows : \n",first_two_rows)
last_two_rows = arr[1:]
print("last two rows : \n",last_two_rows)
center_element = arr[1,1]
print("center element : ",center_element)

first two rows : 
 [[1 2 3]
 [4 5 6]]
last two rows : 
 [[4 5 6]
 [7 8 9]]
center element :  5


### 3. Row-wise and Column-wise Slicing

Using same array:
👉 Extract:

all rows but only 2nd column
only last row
first column from all rows

In [5]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
slicing = arr[:,2]
print("only 2nd columns : ",slicing)
slicing2 = arr[2]
print("only last row : ",slicing2)
slcing3 = arr[:,0]
print("all rows but first columns : ",slcing3)

only 2nd columns :  [3 6 9]
only last row :  [7 8 9]
all rows but first columns :  [1 4 7]


### Filter:

values greater than 10
values less than 10

In [6]:
arr = np.array([12, 5, 8, 20, 3, 15])
filter = arr [ arr > 10 ]
print("values greater than twn : ",filter)
filter2 = arr [arr < 10 ]
print("values less than ten  : ",filter2)

values greater than twn :  [12 20 15]
values less than ten  :  [5 8 3]


### 👉 Using fancy indexing, get elements at indices [0, 2, 4]
👉 Using np.where(), find indices where values > 25

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
indices = [0,2,4]
print("element at index at ", arr[indices])
where=np.where((arr > 25 ))
print("values greater than five : ",arr[where])

element at index at  [10 30 50]
values greater than five :  [30 40 50]


👉 Add:

one element at end
multiple elements
insert element at index 2

In [18]:
arr = np.array([1,2,3,4])
one_element = np.append(arr,5)
print("one element added : ",one_element)
new_array = np.insert(arr,2,[9,8,5])
print("new array : ",new_array)

one element added :  [1 2 3 4 5]
new array :  [1 2 9 8 5 3 4]


### 👉 Remove:

element at index 2
multiple indices [1,3]

In [32]:
arr = np.array([10,20,30,40,50])
element=np.delete(arr,[2])
print("removing element at index two : ",element)
elements = np.delete(arr,[1,3])
print("elements deleted at indices 1 and 3",elements)

removing element at index two :  [10 20 40 50]
elements deleted at indices 1 and 3 [10 30 50]


## 👉 Perform addition a + b
👉 Explain the resulting shape

In [ ]:
a = np.array([1,2,3])
b = np.array([[1],
              [2],
              [3]])


compaitaibility = a.shape == b.shape
print("compaitaibility : ",compaitaibility)
addition = a + b 
print(addition)
print("addition shape : ",addition.shape)



compaitaibility :  False
[[2 3 4]
 [3 4 5]
 [4 5 6]]
addition shape :  (3, 3)


## a new row [5,6]
a new column [7,8]

In [43]:
arr = np.array([[1,2],
                [3,4]])

print("orignal array : ",arr)
new_row = np.array([5,6])
with_new_row = np.vstack((arr,new_row))
print("\nnew row added : \n",with_new_row)
new_col=np.array([[7],[8]])
with_new_col=np.hstack((arr,new_col))
print("\nnew col added : \n",with_new_col)


orignal array :  [[1 2]
 [3 4]]

new row added : 
 [[1 2]
 [3 4]
 [5 6]]

new col added : 
 [[1 2 7]
 [3 4 8]]
