### The Problem: Filtering and Normalizing a Matrix
Objective: Given a 2D NumPy array, filter out rows that contain any negative numbers, and then normalize the remaining rows so that their elements sum to 1. 
Requirements
Create a NumPy array of shape (4, 4) with random integers between -5 and 10 (inclusive).
Filter: Remove any entire row that contains at least one negative number.
Normalize: For the remaining rows, modify them in-place such that the sum of elements in each row is 1.0. 

In [1]:
import numpy as np



In [24]:
array =np.random.randint(-5,11,(4,4))
print("original array " ,array)


original array  [[ 5  2  5  8]
 [ 6  5 -2 -4]
 [ 3  4 -1 -2]
 [ 5  4  7  3]]


In [40]:
condition = (array >= 0).all(axis=1)
# filter
non_negative= array[condition]
print("negative array remove from the matrix : \n",non_negative)
row_sum = np.sum(non_negative,axis=1,keepdims=True)
print("\nadding row wise ",row_sum)
normalized = non_negative / row_sum
print("\nnormalize matrix " ,normalized)

negative array remove from the matrix : 
 [[5 2 5 8]
 [5 4 7 3]]

adding row wise  [[20]
 [19]]

normalize matrix  [[0.25       0.1        0.25       0.4       ]
 [0.26315789 0.21052632 0.36842105 0.15789474]]
