### The Problem: Filtering and Normalizing a Matrix
Objective: Given a 2D NumPy array, filter out rows that contain any negative numbers, and then normalize the remaining rows so that their elements sum to 1. 
Requirements
Create a NumPy array of shape (4, 4) with random integers between -5 and 10 (inclusive).
Filter: Remove any entire row that contains at least one negative number.
Normalize: For the remaining rows, modify them in-place such that the sum of elements in each row is 1.0. 

In [2]:
import numpy as np



In [3]:
array =np.random.randint(-5,11,(4,4))
print("original array " ,array)


original array  [[ 1  8  6  5]
 [ 4  1  8  5]
 [ 7  6  5 -5]
 [-2  1  0  1]]


In [4]:
condition = (array >= 0).all(axis=1)
# filter
non_negative= array[condition]
print("negative array remove from the matrix : \n",non_negative)
row_sum = np.sum(non_negative,axis=1,keepdims=True)
print("\nadding row wise ",row_sum)
normalized = non_negative / row_sum
print("\nnormalize matrix " ,normalized)

negative array remove from the matrix : 
 [[1 8 6 5]
 [4 1 8 5]]

adding row wise  [[20]
 [18]]

normalize matrix  [[0.05       0.4        0.3        0.25      ]
 [0.22222222 0.05555556 0.44444444 0.27777778]]


### 🔹 Problem 1: Row-wise Normalization

Create a 2D NumPy array of random integers (shape 5×4).
Normalize each row so that the sum of each row becomes 1.

👉 Hint: Use sum(axis=1, keepdims=True)

In [5]:
array = np.random.randint(0,15,(5,4))
print("original array : \n",array)
row_sum = np.sum(array,axis=1,keepdims=True)
print("\nrow_sum",row_sum)
normalized=array / row_sum
round = np.round(normalized,1)
print("\nnormalized each rows : ",round)

original array : 
 [[ 7 12  0  1]
 [ 4  9  9  7]
 [13 11  4 14]
 [ 5 10 11 12]
 [ 0  8  0  3]]

row_sum [[20]
 [29]
 [42]
 [38]
 [11]]

normalized each rows :  [[0.4 0.6 0.  0. ]
 [0.1 0.3 0.3 0.2]
 [0.3 0.3 0.1 0.3]
 [0.1 0.3 0.3 0.3]
 [0.  0.7 0.  0.3]]


### Problem 2: Find Duplicate Rows

Given a 2D NumPy array, find all duplicate rows.

In [6]:
matrix = np.array([[1,2],
                    [3,4],
                    [1,2],
                    [5,6]])
unique_rows,count = np.unique(matrix,axis=0,return_counts=True)
duplicate_rows = unique_rows[count > 1]
print("duplicate rows  : ",duplicate_rows)



duplicate rows  :  [[1 2]]


### 🔹 Problem 3: Replace Values Based on Condition

Create an array of size (6×6) with random values from 1 to 20.
Replace:

All values divisible by 3 → -1
All values divisible by 5 → -2

In [7]:
matrix = np.random.randint(1,21,(6,6))
print("matrix : \n",matrix)

#value which are divisable by three are replaced with -1
divby3 = np.where((matrix % 3 == 0), -1,matrix)
print("\nvalue divisable by three  are replaced with -1 : \n",divby3)
#value which are divisable by five are replaced with -2
divby5 = np.where((matrix % 5 == 0),-2,matrix)
print("\nvalues are divisble by five are replaced with -2 : ",divby5)



matrix : 
 [[18 20 18 11 16 16]
 [ 8  7  9 11 11 17]
 [16 12 10 13  3 16]
 [ 4 14 10  2 15 14]
 [11 13  6 10  3 19]
 [ 7  4 10  5 19  8]]

value divisable by three  are replaced with -1 : 
 [[-1 20 -1 11 16 16]
 [ 8  7 -1 11 11 17]
 [16 -1 10 13 -1 16]
 [ 4 14 10  2 -1 14]
 [11 13 -1 10 -1 19]
 [ 7  4 10  5 19  8]]

values are divisble by five are replaced with -2 :  [[18 -2 18 11 16 16]
 [ 8  7  9 11 11 17]
 [16 12 -2 13  3 16]
 [ 4 14 -2  2 -2 14]
 [11 13  6 -2  3 19]
 [ 7  4 -2 -2 19  8]]


### Problem 4: Matrix Row Swap

Given a matrix:
Swap the first and last rows.

[[1,2,3],
 [4,5,6],
 [7,8,9]]

In [8]:
matrix = np.array([[1,2,3],
                   [4,3,2],
                   [5,6,7],
                   [8,7,6],
                   [5,2,1]])
matrix [[0,4]] = matrix[[4,0]]
print("swaping ist and last rows : \n ",matrix)
# swaping row two and 0 ,row 4 and 3
matrix[[2,0,4,3]] = matrix [[0,2,3,4]]
print("swaping row two and 0 ,row 4 and 3 : \n ",matrix)

swaping ist and last rows : 
  [[5 2 1]
 [4 3 2]
 [5 6 7]
 [8 7 6]
 [1 2 3]]
swaping row two and 0 ,row 4 and 3 : 
  [[5 6 7]
 [4 3 2]
 [5 2 1]
 [1 2 3]
 [8 7 6]]


### 1. Row-wise Normalization

Create a random 5x4 matrix and normalize each row (divide each element by the row sum).

In [14]:
matrixx = np.random.randint(0,13,(5,4))
print("original matrix : \n",matrixx)
row_sum = np.sum(matrixx,axis=1,keepdims=True)
normalized =np.round( matrixx / row_sum ,2)
print("matrix are normlaized row wise : \n",normalized)

original matrix : 
 [[ 8  5 10  8]
 [ 5  2  8 11]
 [ 5  4 10 12]
 [11  6 11  7]
 [ 5  1  6  8]]
matrix are normlaized row wise : 
 [[0.26 0.16 0.32 0.26]
 [0.19 0.08 0.31 0.42]
 [0.16 0.13 0.32 0.39]
 [0.31 0.17 0.31 0.2 ]
 [0.25 0.05 0.3  0.4 ]]


### 🔹 4. Column-wise Mean and Std

Create a 4x5 matrix and compute:

Mean of each column
Standard deviation of each column

In [18]:
mat = np.random.randint(0,9,(4,5))
print("matrix : \n ",mat)
column_wise_mean=np.mean(mat,axis=0)
print("columns wise mean : ",column_wise_mean)
column_std = np.std(mat,axis=0)
column_std = np.round(column_std,3)
print("standard deviation of each column : ",column_std)

matrix : 
  [[2 0 3 5 4]
 [8 1 1 0 0]
 [4 4 8 5 1]
 [0 4 2 4 3]]
columns wise mean :  [3.5  2.25 3.5  3.5  2.  ]
standard deviation of each column :  [2.958 1.785 2.693 2.062 1.581]


### 7. Sort by Second Column

Given:

In [21]:
arr = np.array([[3,5],
                [1,2],
                [4,1]])
print(np.sort(arr[:,1],axis=0))


[1 2 5]
