# begginer level problems on numpy

In [13]:
import numpy as np
import pandas as pd

In [3]:
array=np.arange(11)
print("array from one to ten : ",array)

print("\n shape of array : ",array.shape)
print("\n size of array :",array.size)

array from one to ten :  [ 0  1  2  3  4  5  6  7  8  9 10]

 shape of array :  (11,)

 size of array : 11


In [4]:
two_darray=np.random.random((3,3))
print("two dimensional array : \n",two_darray)
print("\nshap of the two d array : ",two_darray.shape)
print("\n size of the two d array : ",two_darray.size)
print("data type of the two d array  :",two_darray.dtype)

two dimensional array : 
 [[0.06614247 0.50909613 0.81744272]
 [0.61795665 0.89676198 0.10298431]
 [0.80466269 0.98204116 0.96699003]]

shap of the two d array :  (3, 3)

 size of the two d array :  9
data type of the two d array  : float64


### creating array of zeros and ones

In [5]:
zeros_array =np.zeros((5))
print("five  zeros array : ",zeros_array)
ones_array= np.ones((5))
print("five ones array : ",ones_array)

five  zeros array :  [0. 0. 0. 0. 0.]
five ones array :  [1. 1. 1. 1. 1.]


### creating array of even number from one to twenty

In [6]:
even_array = np.arange(0,20,2)
print("even numbers array : ",even_array)

even numbers array :  [ 0  2  4  6  8 10 12 14 16 18]


### Create an array from 1 to 12 and reshape it into a 3×4 matrix.

In [7]:
array = np.arange(12)
print("original array  : ",array)

reshaped_array = array.reshape((3,4))
print("\nreshaped array : \n",reshaped_array)

original array  :  [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped array : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


### slicing concept

In [8]:
array = np.arange(20)
print("orignal array " ,array)
print("\nslicing ist three element : ",array[0:3])
print("\nslicing last two element from array : ",array[18:20])

orignal array  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

slicing ist three element :  [0 1 2]

slicing last two element from array :  [18 19]


### addition and multiplication

In [9]:
ist_array = np.array([2,3,6,9])
second_array = np.array([3,2,5,1])
print("addition of the two array : ",ist_array + second_array)

print("\n multiplication of two array : ",ist_array * second_array)

addition of the two array :  [ 5  5 11 10]

 multiplication of two array :  [ 6  6 30  9]


### Create an array and find:

maximum value
minimum value

In [10]:
array = np.array([90,-4,30,3000,2000,-100,80000000])
print("maximum in the array : ",array.max())
print("minimum in the array : ",array.min())

maximum in the array :  80000000
minimum in the array :  -100


### Mean and Sum
Calculate:

sum
mean
of an array

In [11]:
array = np.array([5,6,4,3,77,88,33,99])
print("sum of the array : ",array.sum())
print("mean of the array : ",array.mean())

sum of the array :  315
mean of the array :  39.375


### 👉 Extract all elements greater than 5 from your array:

In [12]:
array = np.array([5,6,4,3,77,88,33,99])
greater = array[array > 5]
print("greater element than 5  is : ",greater)

greater element than 5  is :  [ 6 77 88 33 99]
