In [13]:
import numpy as np

### checking shape datatype and size of the array very basic problem

In [14]:
array_one =np.array([1, 2, 3, 4, 5])
print("array shape : ",array_one.shape)
print("array_one",array_one.size)
print("array_one",array_one.dtype)

array shape :  (5,)
array_one 5
array_one int64


### creating matrix of zeros and ones

In [15]:
matrix_one = np.zeros((3,4))
print("null matrix : \n",matrix_one)
matrix_two = np. ones((3,4))
print("identity matrix :\n ",matrix_two)

null matrix : 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
identity matrix :
  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### creating matrix of random number between one and hundred of 4 X 4 and finding min,max,mean,sum

In [16]:
matrix_three = np.random.randint(1,100,(4,4))
print("matrix : \n",matrix_three)
print("min of the matrix : ",np.min(matrix_three))
print("max of the matrix : ",np.max(matrix_three))
print("mean of the matrix : ",np.mean(matrix_three))
print("sum of the matrix : ",np.sum(matrix_three))




matrix : 
 [[55 46 11 56]
 [95 70 85 76]
 [39 48 71 25]
 [38 62 51 83]]
min of the matrix :  11
max of the matrix :  95
mean of the matrix :  56.9375
sum of the matrix :  911


## slicing

In [17]:
array_two = np.arange(10)
extract = array_two[2:7]
print("extract element from index 2 to 7 : ",extract)


extract element from index 2 to 7 :  [2 3 4 5 6]


### Create a 5x5 array with numbers 0 to 24. Extract the middle 3x3 subarray.

In [26]:
matrix_four=np.random.randint(0,24,(5,5))
print("orignal matrix :\n ",matrix_four)
extract = matrix_four[1:4,1:4]
print("\nmiddle of the matrix\n ",extract)

orignal matrix :
  [[13  6 20 16  1]
 [ 7 22 23 13  0]
 [ 5 13  1  5 19]
 [ 6 14 20 18  3]
 [ 9 16  6 17  5]]

middle of the matrix
  [[22 23 13]
 [13  1  5]
 [14 20 18]]


### Generate an array of 10 evenly spaced numbers between 0 and 1 (inclusive).

In [27]:
array_three = np.linspace(0,1,10)
print(array_three)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


### From a 4x4 array, extract all even rows and odd columns.

In [33]:
matrix_five =np.random.randint(0,10,(4,4))
print("matrix : \n",matrix_five)
extraxt_even_rows = matrix_five[0:4:2]
print("extracting all even rows from the matrix : \n",extraxt_even_rows)
extract_odd_col=matrix_five[:,1:4:2]
print("extracting all odd columns : \n ",extract_odd_col)

result = matrix_five[0:4:2, 1:4:2]  # Rows 0,2 and Columns 1,3
print("Elements in even rows AND odd columns:")
print(result)


matrix : 
 [[4 2 2 9]
 [9 6 0 6]
 [6 1 5 4]
 [5 8 1 7]]
extracting all even rows from the matrix : 
 [[4 2 2 9]
 [6 1 5 4]]
extracting all odd columns : 
  [[2 9]
 [6 6]
 [1 4]
 [8 7]]
Elements in even rows AND odd columns:
[[2 9]
 [1 4]]


### Reshape a 1D array of 12 elements into a 3x4 matrix. Then flatten it back.

In [38]:
arr = np.arange(0,12)
print("original array :  ",arr)
print("\nreshape it to 3 X 4 : \n",arr.reshape(3,4))
print("\nflatten it back :",arr.flatten())

original array :   [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape it to 3 X 4 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

flatten it back : [ 0  1  2  3  4  5  6  7  8  9 10 11]


### Stack two 2x2 arrays vertically (row-wise) and horizontally (column-wise

In [42]:
arr = np .array([[1,2],
                 [3,4]])


arrr = np.array([[3,4],
                 [5,6]])
print("array one : \n",arr)
print("\narray two : \n",arrr)
vstack =np.vstack((arr,arrr))
print("row wise  : \n",vstack)
hstack = np.hstack((arr,arrr))
print("column wise : \n",hstack)

array one : 
 [[1 2]
 [3 4]]

array two : 
 [[3 4]
 [5 6]]
row wise  : 
 [[1 2]
 [3 4]
 [3 4]
 [5 6]]
column wise : 
 [[1 2 3 4]
 [3 4 5 6]]
