### The Problem: Filtering and Normalizing a Matrix
Objective: Given a 2D NumPy array, filter out rows that contain any negative numbers, and then normalize the remaining rows so that their elements sum to 1. 
Requirements
Create a NumPy array of shape (4, 4) with random integers between -5 and 10 (inclusive).
Filter: Remove any entire row that contains at least one negative number.
Normalize: For the remaining rows, modify them in-place such that the sum of elements in each row is 1.0. 

In [6]:
import numpy as np



In [7]:
array =np.random.randint(-5,11,(4,4))
print("original array " ,array)


original array  [[-4 -2  5  0]
 [-1  5  5 -3]
 [-5  9  8 -1]
 [-1  2  3  8]]


In [8]:
condition = (array >= 0).all(axis=1)
# filter
non_negative= array[condition]
print("negative array remove from the matrix : \n",non_negative)
row_sum = np.sum(non_negative,axis=1,keepdims=True)
print("\nadding row wise ",row_sum)
normalized = non_negative / row_sum
print("\nnormalize matrix " ,normalized)

negative array remove from the matrix : 
 []

adding row wise  []

normalize matrix  []


### 🔹 Problem 1: Row-wise Normalization

Create a 2D NumPy array of random integers (shape 5×4).
Normalize each row so that the sum of each row becomes 1.

👉 Hint: Use sum(axis=1, keepdims=True)

In [28]:
array = np.random.randint(0,15,(5,4))
print("original array : \n",array)
row_sum = np.sum(array,axis=1,keepdims=True)
print("\nrow_sum",row_sum)
normalized=array / row_sum
round = np.round(normalized,1)
print("\nnormalized each rows : ",round)

original array : 
 [[ 1  9  8  5]
 [ 9 13  8 11]
 [13  9  1  5]
 [ 5 11  8 14]
 [ 2 12  3  8]]

row_sum [[23]
 [41]
 [28]
 [38]
 [25]]

normalized each rows :  [[0.  0.4 0.3 0.2]
 [0.2 0.3 0.2 0.3]
 [0.5 0.3 0.  0.2]
 [0.1 0.3 0.2 0.4]
 [0.1 0.5 0.1 0.3]]


### Problem 2: Find Duplicate Rows

Given a 2D NumPy array, find all duplicate rows.

In [43]:
matrix = np.array([[1,2],
                    [3,4],
                    [1,2],
                    [5,6]])
unique_rows,count = np.unique(matrix,axis=0,return_counts=True)
duplicate_rows = unique_rows[count > 1]
print("duplicate rows  : ",duplicate_rows)



duplicate rows  :  [[1 2]]


### 🔹 Problem 3: Replace Values Based on Condition

Create an array of size (6×6) with random values from 1 to 20.
Replace:

All values divisible by 3 → -1
All values divisible by 5 → -2

### Problem 4: Matrix Row Swap

Given a matrix:
Swap the first and last rows.

[[1,2,3],
 [4,5,6],
 [7,8,9]]